export const GET_LOCATION = 'GET_LOCATION';
export const ADD_LOCATION = 'ADD_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const GET_SINGLE_LOCATION = 'GET_SINGLE_LOCATION';
